### ISSUE TITLE
Error while loading package

### ISSUE THREAD

**Issue by fernandoquintal** [GearPlug/surveymonkey-python#4]
Hello,

Just tried to use the package as the tutorial describes, but "Client" is not found at "client". How can I fix it?

![image](https://user-images.githubusercontent.com/43733280/80998200-e88aef00-8e18-11ea-807a-0cbc05d19f8a.png)

Best Regards, Fernando

**Comment by eanunez** [comment]
Hi Fernando,

I think the instruction was assuming that you have the client available in your root directory. the way I called the client is by `from surveymonkey.client import Client`
I hope this solves your problem.
